import { useEffect, useState } from 'react'
import { Activity, BadgeCheck, BookOpen, ChevronRight, CircleAlert, Clock3, Code2, Command, FileCheck2, FileSearch, Fingerprint, History, LayoutDashboard, Library, LockKeyhole, Play, RefreshCw, ScanLine, Settings2, ShieldCheck, SlidersHorizontal, Terminal, Upload, X } from 'lucide-react'

type Finding = {rule_id:string;severity:string;message:string;evidence:string;remediation:string;location:string|null}
type Report = {run_id:string;skill:{path:string;name:string;sha256:string};policy:{profile:string;source:string;sha256:string};engine:{version:string};decision:{verdict:string;blocking_findings:number};summary:{critical:number;high:number;medium:number;low:number;passed:number};checks:{name:string;passed:boolean;finding_count:number;duration_ms:number}[];findings:Finding[];duration_ms:number;equivalent_cli:string}
type View = 'Overview'|'Scan'|'Findings'|'Policies'|'History'|'Certificates'

const nav = [
  ['Overview', LayoutDashboard],['Scan', ScanLine],['Findings', CircleAlert],['Policies', SlidersHorizontal],['History', History],['Certificates', BadgeCheck]
] as const
const utilities = [['Rule catalogue', Library],['CI integration', Code2],['Documentation', BookOpen]] as const
const fallback: Report = {
  run_id:'run_local_demo',skill:{path:'examples/invalid-skill/SKILL.md',name:'customer-support-skill',sha256:'9c44ef5e1253a16cdbcd3c77220c3f1e'},policy:{profile:'recommended-v2',source:'./skilltrustops.yaml',sha256:'a4d9fb73c218'},engine:{version:'0.1.0'},decision:{verdict:'blocked',blocking_findings:2},summary:{critical:2,high:1,medium:2,low:0,passed:1},duration_ms:184,equivalent_cli:'skilltrustops security "./examples/invalid-skill/SKILL.md" --policy "./skilltrustops.yaml" --format json',checks:[{name:'specification',passed:true,finding_count:0,duration_ms:18},{name:'security',passed:false,finding_count:3,duration_ms:112},{name:'privacy',passed:false,finding_count:2,duration_ms:54}],findings:[{rule_id:'STO-SEC-014',severity:'critical',message:'Remote script execution',evidence:'curl -sSL https://setup.example.dev/install.sh | bash',remediation:'Download the script, verify its checksum, and run a pinned local copy after review.',location:'SKILL.md:48'},{rule_id:'STO-SEC-003',severity:'critical',message:'Embedded API credential',evidence:'SUPPORT_API_KEY="sk_live_4fa98d..."',remediation:'Remove the credential and load it from an approved secret store at runtime.',location:'SKILL.md:73'},{rule_id:'STO-PRIV-001',severity:'medium',message:'Customer email address in example',evidence:'Contact the customer at ari@example.com',remediation:'Replace real or realistic personal data with an obvious placeholder.',location:'SKILL.md:91'}]
}

function verdictLabel(v:string){return v==='admissible'?'ADMISSIBLE':v==='needs_remediation'?'NEEDS REMEDIATION':'BLOCKED'}
function titleCase(v:string){return v.replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}

export function App(){
  const [view,setView]=useState<View>('Overview'); const [report,setReport]=useState<Report>(fallback); const [selected,setSelected]=useState(0); const [path,setPath]=useState('examples/invalid-skill/SKILL.md'); const [file,setFile]=useState<{name:string,content:string}|null>(null); const [running,setRunning]=useState(false); const [copied,setCopied]=useState(false); const [error,setError]=useState(''); const [history,setHistory]=useState<Report[]>([])
  useEffect(()=>{fetch('/api/demo').then(r=>r.ok?r.json():Promise.reject()).then(setReport).catch(()=>{})},[])
  async function inspect(){setRunning(true);setError('');try{const endpoint=file?'/api/scans/content':'/api/scans';const body=file?{filename:file.name,content:file.content}:{skill_path:path};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Inspection failed');setReport(data);setHistory(items=>[data,...items.filter(x=>x.run_id!==data.run_id)]);setView('Overview')}catch(e){setError(e instanceof Error?e.message:'Inspection failed')}finally{setRunning(false)}}
  function copyCli(){navigator.clipboard?.writeText(report.equivalent_cli);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brandmark"><ShieldCheck size={19}/></div><div><b>SkillTrustOps</b><span>STUDIO</span></div></div>
      <nav>{nav.map(([label,Icon])=><button key={label} className={view===label?'active':''} onClick={()=>setView(label)}><Icon size={16}/>{label}{label==='Findings'&&report.findings.length>0&&<em>{report.findings.length}</em>}</button>)}</nav>
      <div className="side-label">TOOLS</div><nav className="utilities">{utilities.map(([label,Icon])=><button key={label}><Icon size={15}/>{label}</button>)}</nav>
      <div className="local-card"><div><span className="live-dot"/>LOCAL MODE</div><p>No files uploaded<br/>No external model calls</p><button><Settings2 size={14}/>Local settings</button></div>
    </aside>
    <main><header><div className="crumb"><span>SkillTrustOps</span><ChevronRight size={14}/><b>{view}</b></div><div className="header-actions"><span className="privacy"><LockKeyhole size={13}/>Local only</span><button className="icon-button"><Command size={15}/><span>K</span></button><div className="avatar">RC</div></div></header>
      <div className="lifecycle">{['Select skill','Resolve policy','Inspect','Scan','Apply gates','Explain','Fix + rescan','Compare','Certify'].map((s,i)=><div className={i<6?'done':i===6?'current':''} key={s}><span>{i<6?'✓':i+1}</span><small>{s}</small></div>)}</div>
      {view==='Overview'&&<Overview report={report} onFindings={()=>setView('Findings')} onScan={inspect} running={running}/>} 
      {view==='Scan'&&<Scan path={path} setPath={setPath} file={file} setFile={setFile} inspect={inspect} running={running} error={error} cli={report.equivalent_cli} copyCli={copyCli} copied={copied}/>} 
      {view==='Findings'&&<Findings report={report} selected={selected} setSelected={setSelected}/>} 
      {view==='Policies'&&<Policy report={report}/>} 
      {view==='History'&&<HistoryView reports={history.length?history:[report]} open={(r)=>{setReport(r);setView('Overview')}}/>}
      {view==='Certificates'&&<Certificates report={report}/>} 
    </main>
  </div>
}

function Overview({report,onFindings,onScan,running}:{report:Report,onFindings:()=>void,onScan:()=>void,running:boolean}){return <section className="page"><div className="page-heading"><div><p className="eyebrow">LATEST TRUST DECISION</p><h1>{report.skill.name}</h1><p className="subtle mono">{report.skill.path}</p></div><button className="secondary"><History size={15}/>View history</button></div>
  <article className="decision-card"><div className="decision-top"><div><div className="meta"><span>{report.policy.profile}</span><i/> <span>Local</span><i/> <span>{report.duration_ms} ms</span></div><h2 className={'verdict '+report.decision.verdict}>{verdictLabel(report.decision.verdict)}</h2><p>{report.decision.verdict==='admissible'?'All required checks passed. This skill is eligible for certification.':report.decision.blocking_findings?`${report.decision.blocking_findings} security gates prevent this skill from being admitted`:`${report.findings.length} findings require remediation before admission`}</p></div><div className={'decision-glyph '+report.decision.verdict}>{report.decision.verdict==='admissible'?<ShieldCheck size={32}/>:<X size={32}/>}</div></div>
    <div className="checks">{report.checks.map(c=><div className={c.passed?'pass':'fail'} key={c.name}><span>{c.passed?'✓':'!'}</span><div><b>{titleCase(c.name)}</b><small>{c.passed?'Passed':`${c.finding_count} findings`}</small></div></div>)}</div>
    <div className="summary"><div><strong>{report.summary.critical}</strong><span className="critical-dot"/>Critical</div><div><strong>{report.summary.high}</strong><span className="high-dot"/>High</div><div><strong>{report.summary.medium}</strong><span className="medium-dot"/>Medium</div><div><strong>{report.summary.passed}</strong><span className="pass-dot"/>Checks passed</div></div>
    <div className="blockers"><div className="section-row"><h3>{report.findings.length?'Findings requiring attention':'Findings'}</h3>{report.findings.length>0&&<button onClick={onFindings}>View all {report.findings.length}<ChevronRight size={14}/></button>}</div>{report.findings.length===0?<div className="no-findings"><ShieldCheck size={18}/><div><b>No findings detected</b><span>Specification, security, and privacy checks all passed.</span></div></div>:report.findings.slice(0,2).map(f=><button className="blocker" key={f.rule_id} onClick={onFindings}><span className={'severity '+f.severity}>{f.severity[0].toUpperCase()}</span><code>{f.rule_id}</code><b>{f.message}</b><span className="location">{f.location||'SKILL.md'}</span><ChevronRight size={16}/></button>)}</div>
    <div className="decision-actions">{report.findings.length>0&&<><button className="primary" onClick={onFindings}><FileSearch size={16}/>Review findings</button><button className="secondary" onClick={onFindings}>View remediation plan</button></>}<button className="ghost" onClick={onScan} disabled={running}><RefreshCw size={15} className={running?'spin':''}/>{running?'Inspecting…':'Run again'}</button></div></article>
  <div className="lower-grid"><article><div className="panel-head"><div><h3>Decision provenance</h3><p>Everything required to reproduce this result.</p></div><Fingerprint size={19}/></div><dl><div><dt>Policy source</dt><dd className="mono">{report.policy.source}</dd></div><div><dt>Policy hash</dt><dd className="mono">{report.policy.sha256.slice(0,16)}…</dd></div><div><dt>Skill hash</dt><dd className="mono">{report.skill.sha256.slice(0,16)}…</dd></div><div><dt>Engine</dt><dd className="mono">v{report.engine.version}</dd></div></dl></article><article className={report.decision.verdict==='admissible'?'success-panel':''}><div className="panel-head"><div><h3>{report.decision.verdict==='admissible'?'Ready for certification':'Next action'}</h3><p>{report.decision.verdict==='admissible'?'The trust decision is complete and reproducible.':'Resolve findings before certification.'}</p></div>{report.decision.verdict==='admissible'?<BadgeCheck size={19}/>:<Activity size={19}/>}</div>{report.decision.verdict==='admissible'?<div className="next-action success"><div>✓</div><p><b>All admission gates passed</b><span>Review the certificate requirements and create a verifiable trust record.</span></p></div>:<><div className="next-action"><div>01</div><p><b>{report.findings[0]?.message||'Review required finding'}</b><span>{report.findings[0]?.remediation||'Resolve the reported issue and run the inspection again.'}</span></p></div><button className="text-button" onClick={onFindings}>Open remediation workspace <ChevronRight size={14}/></button></>}</article></div>
  </section>}

function Scan({path,setPath,file,setFile,inspect,running,error,cli,copyCli,copied}:{path:string,setPath:(v:string)=>void,file:{name:string,content:string}|null,setFile:(v:{name:string,content:string}|null)=>void,inspect:()=>void,running:boolean,error:string,cli:string,copyCli:()=>void,copied:boolean}){async function choose(f:File|undefined){if(f)setFile({name:f.name,content:await f.text()})}return <section className="page narrow"><div className="page-heading"><div><p className="eyebrow">LOCAL INSPECTION</p><h1>Inspect a skill</h1><p className="subtle">Resolve policy, apply hard gates, and produce an explainable decision.</p></div></div><div className="scan-grid"><article><label>SKILL FILE</label><label className={'dropzone '+(file?'has-file':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><Upload size={24}/><b>{file?file.name:'Choose or drop a local SKILL.md'}</b><span>{file?`${file.content.length.toLocaleString()} bytes ready for local inspection`:'Content never leaves this device'}</span><input className="file-input" type="file" accept=".md,text/markdown" onChange={e=>choose(e.target.files?.[0])}/><button type="button" className="secondary">{file?'Replace file':'Browse files'}</button></label><div className="path-fallback"><span>or inspect a local path</span><input value={path} onChange={e=>{setFile(null);setPath(e.target.value)}} aria-label="Skill path"/></div>{file&&<button className="clear-file" onClick={()=>setFile(null)}><X size={12}/>Remove selected file</button>}<label>POLICY</label><button className="select"><div><ShieldCheck size={16}/><span><b>recommended-v2</b><small>Repository policy · Valid</small></span></div><ChevronRight size={15}/></button><label>SCAN SCOPE</label><div className="scope"><button className="selected"><FileCheck2 size={16}/>All checks</button><button>Specification</button><button>Security</button><button>Privacy</button></div>{error&&<div className="scan-error"><CircleAlert size={14}/>{error}</div>}<button className="primary inspect" onClick={inspect} disabled={running}><Play size={16}/>{running?'Inspecting locally…':'Inspect skill'}</button></article><aside className="expect"><h3>Inspection boundary</h3><p>SkillTrustOps is deterministic by design.</p><div><b>WILL</b><span>✓ Read the selected skill</span><span>✓ Apply recommended-v2</span><span>✓ Inspect specification, security and privacy</span></div><div><b>WILL NOT</b><span>✓ Execute skill code</span><span>✓ Make external network requests</span><span>✓ Upload outside this local service</span><span>✓ Call an external LLM</span></div></aside></div><div className="cli-box"><div><Terminal size={15}/><span>Equivalent CLI command</span></div><code>{cli}</code><button onClick={copyCli}>{copied?'Copied':'Copy'}</button></div></section>}

function Findings({report,selected,setSelected}:{report:Report,selected:number,setSelected:(n:number)=>void}){const f=report.findings[selected]||fallback.findings[0];return <section className="findings-page"><div className="find-head"><div><p className="eyebrow">EVIDENCE REVIEW</p><h1>Findings</h1></div><span>{report.findings.length} unresolved</span></div><div className="explorer"><aside className="filters"><b>FILTERS</b><label>Severity</label>{['Critical','High','Medium','Low'].map(x=><button key={x}><span className={x.toLowerCase()}/>{x}<em>{(report.summary as any)[x.toLowerCase()]||0}</em></button>)}<label>Category</label><button>Security <em>3</em></button><button>Privacy <em>2</em></button></aside><div className="finding-list">{report.findings.map((item,i)=><button className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={item.rule_id}><div><code>{item.rule_id}</code><span className={'tag '+item.severity}>{item.severity}</span></div><b>{item.message}</b><small>{item.location} · Blocks admission</small></button>)}</div><article className="evidence"><div className="evidence-head"><div><code>{f.rule_id}</code><h2>{f.message}</h2></div><span className={'tag '+f.severity}>{f.severity}</span></div><div className="source-title"><span>SKILL.md</span><span>{f.location}</span></div><pre><span>46 │ # Install dependency</span>{'\n'}<span>47 │ ```bash</span>{'\n'}<mark>48 │ {f.evidence}</mark>{'\n'}<span>49 │ ```</span></pre><div className="explain"><h3>Why this matters</h3><p>Unverified content can change without review and execute with the permissions of the host process. This violates the selected policy’s hard gate.</p><h3>Recommended change</h3><p>{f.remediation}</p></div><button className="primary"><Code2 size={15}/>Open remediation</button></article></div></section>}

function Policy({report}:{report:Report}){return <section className="page"><div className="page-heading"><div><p className="eyebrow">POLICY STUDIO</p><h1>{report.policy.profile}</h1><p className="subtle">One policy model, shown in guided and code views.</p></div><span className="valid">✓ VALID</span></div><div className="policy-grid"><article><h3>Guided mode</h3>{['Secret detection','Block eval','Block destructive shell commands','Block remote script piping','Email addresses','Phone numbers','Credit cards'].map((x,i)=><label className="toggle" key={x}><span><small>{i<4?'SECURITY':'PRIVACY'}</small>{x}</span><input type="checkbox" defaultChecked/><i/></label>)}</article><article className="code-panel"><div><h3>Code mode</h3><span>skilltrustops.yaml</span></div><pre>{`version: 1\nprofile: recommended-v2\n\nchecks:\n  security:\n    enabled: true\n    dangerous_code:\n      block_eval: true\n      block_destructive_shell: true\n      block_remote_pipe: true\n  privacy:\n    enabled: true`}</pre></article></div></section>}
function Placeholder({icon:Icon,title,text}:{icon:any,title:string,text:string}){return <section className="page"><div className="empty"><Icon size={28}/><h1>{title}</h1><p>{text}</p><button className="secondary">Learn how it works</button></div></section>}
function HistoryView({reports,open}:{reports:Report[],open:(r:Report)=>void}){return <section className="page"><div className="page-heading"><div><p className="eyebrow">LOCAL RECORD</p><h1>Scan history</h1><p className="subtle">Decisions created during this Studio session.</p></div></div><article className="history-table">{reports.map(r=><button key={r.run_id} onClick={()=>open(r)}><span className={'history-verdict '+r.decision.verdict}>{verdictLabel(r.decision.verdict)}</span><div><b>{r.skill.name}</b><small className="mono">{r.run_id}</small></div><span>{r.findings.length} findings</span><span className="mono">{r.duration_ms} ms</span><ChevronRight size={15}/></button>)}</article></section>}
function Certificates({report}:{report:Report}){const ok=report.decision.verdict==='admissible';const requirements:[string,boolean][]=[['Policy is valid',true],['Skill content hash is known',!!report.skill.sha256],['No critical security finding',report.summary.critical===0],['No blocking privacy violation',!report.findings.some(f=>f.rule_id.includes('PRIV')&&['critical','high'].includes(f.severity))],['All mandatory specification rules pass',report.checks.find(c=>c.name==='specification')?.passed===true],['Recognised engine version',!!report.engine.version],['Evidence included in report',true]];return <section className="page"><div className="page-heading"><div><p className="eyebrow">STRICT CERTIFICATION</p><h1>SkillTrustOps Verified</h1><p className="subtle">Certification is granted only when every mandatory trust condition passes.</p></div></div><article className="certificate-card"><ShieldCheck size={30}/><h2>{ok?'Ready to certify':'Certification unavailable'}</h2><p>{ok?'This decision satisfies all current policy gates.':'Resolve the failed requirements and run the inspection again.'}</p><div>{requirements.map(([label,pass])=><span className={pass?'met':'unmet'} key={label}>{pass?'✓':'×'} {label}</span>)}</div><button className="primary" disabled={!ok}><BadgeCheck size={16}/>Create certificate</button></article></section>}
